# Generated by Django 5.0.2 on 2024-02-21 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odejda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(max_length=300, upload_to='')),
                ('skidka', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ohota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(max_length=300, upload_to='')),
                ('skidka', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rybalka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(max_length=300, upload_to='')),
                ('skidka', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Korzina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('summa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('odejda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.odejda')),
                ('ohota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ohota')),
                ('rybalka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.rybalka')),
            ],
        ),
    ]
