# Generated by Django 5.0.2 on 2024-02-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korzina',
            name='odejda',
        ),
        migrations.RemoveField(
            model_name='korzina',
            name='ohota',
        ),
    ]
