# Generated by Django 5.0.2 on 2024-02-21 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_korzina_odejda_remove_korzina_ohota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korzina_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('summa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ohota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ohota')),
            ],
        ),
        migrations.CreateModel(
            name='Korzina_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('summa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('odejda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.odejda')),
            ],
        ),
    ]
